function classes = GetShrec2010ClassNames

classes = {...
    'holes',...
    'isometry',...
    'localscale',...
    'microholes',...
    'noise',...
    'sampling',...
    'scale',...
    'shotnoise',...
    'topology'};