function classes = GetShrec2011ClassNames
%%
classes = {...
    'affine',...
    'holes',...
    'isometry',...
    'microholes',...
    'noise',...
    'partial',...
    'rasterize',...
    'sampling',...
    'scaling',...
    'shotnoise',...
    'view'};